version: "3.9"
services:
  flask-app: #Docker image : raji2306/flask-app:1.0
    image: mine
    restart: always
    depends_on:
    - db
    links :
    - db
    ports:
      - "5008:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: myflaskapp
      DATABASE_URL: mysql://root:example@db:3306/myflaskapp?charset=utf8mb4
    networks:
      - my_network
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=myflaskapp
    ports:
      - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  mysql-data:
